ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -h /home/alpine -D alpine \
    && apk add --no-cache --purge -uU curl py-pygments \
    && VERSION="$(curl -sX GET "https://api.github.com/repos/gohugoio/hugo/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_^v__')" \
    && curl -o /tmp/hugo.tar.gz -SL https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz \
    && tar xzf /tmp/hugo.tar.gz -C /usr/local/bin/ \
    && rm -rf /var/cache/apk/* /tmp/*
#
# VOLUME /home/alpine/project
# USER alpine
# WORKDIR /home/alpine/project
EXPOSE 1313
# ENTRYPOINT ["/bin/bash"]
# ENTRYPOINT ["hugo"]
